### ISSUE TITLE
ggplot subset faceting

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#150]
Base iNZightPlots uses a matrix (more akin to `facet_wrap`) when only one subset variable (`g1`), while the ggplot graphs seem to be using `facet_grid`. 

- the plots are visually different
- if you have more than a few levels, the plots quickly become useless

It would be better to use `facet_wrap` when there's just one subsetting variable, and `facet_grid` if both g1 and g2 are set, _and_ `g2.level == '_MULTI'`).

![Screenshot from 2019-09-26 13-32-56](https://user-images.githubusercontent.com/5061277/65651330-36a96a00-e062-11e9-8832-410a314c7307.png)
![Screenshot from 2019-09-26 13-33-09](https://user-images.githubusercontent.com/5061277/65651333-390bc400-e062-11e9-9de4-02dfbc057d16.png)

**Comment by tmelliott** [comment]
@daniel-barnett would this be much work? 
PS: no rush, as I probably won't be ready to submit plots pkg to CRAN until next month anyway!

**Comment by daniel-barnett** [comment]
It shouldn't be too much, so it'll be done for the CRAN submission
