### ISSUE TITLE
ggplots: factor order reversed?

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#270]
In num x cat, the y-axis in dot plots runs top-to-bottom in the default plots (female on top). However ggplots are the other way around (male on top). @daniel-barnett is it an easy fix to swap this so the order is the same across plots?

**Comment by daniel-barnett** [comment]
Yep, probably. I was just doing some testing for the ggplots last night so this ties in well with where I am atm :slightly_smiling_face:
