### ISSUE TITLE
exportHTML return val (instead of browse)

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#30]
Instead of using `browse()` inside the `exportHTML` function [on this line](https://github.com/iNZightVIT/iNZightPlots/blob/master/R/exportHTML.R#L137), can we instead return the URL?

```{r}
url <- exportHTML(...)

# Then if the user wants to:
browse(url)
```

This is needed so the functionality can be implemented in Shiny.

**Comment by tmelliott** [comment]
@ysoh286 tagging you so you get an email :smile:

**Comment by ysoh286** [comment]
Do you mean just return the `file.path(file)`? Could just remove the `browseURL()` function. Do you need the option to browse within `exportHTML()` function as well?

**Comment by tmelliott** [comment]
1. @ysoh286 Tag me and then I'll get an email notifying me you've commented and get back to you sooner 👍 

2. TBH I'd remove the browse completely, and possibly use something similar to the [htmlwidgets](https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L26) package. The `html_print` function actually comes from the [htmltools](https://github.com/rstudio/htmltools/blob/master/R/html_print.R#L41) package. If you have a look through those packages/functions, you might get an idea of how they're solving a fairly similar problem. You could use a setup where you return an `inzfile` object or something (you can come up with an appropriate name) that has a `print.inzfile` method, that takes an optional "viewer" argument as they've done in `htmlwidgets`. That way, the user's experience would be:
```{r}
fp = exportHTML(myplot)
fp # this will open the file in a browser

# and on the iNZight Lite shiny app,
print(fp, viewer = something)
```

It doesn't need to be nearly as complicated as the `htmlwidgets` version, and simply returning the URL is probably good enough. Having a "print" method just makes it easier for users using the package from R to load it :smile: 

3. Just put it on whichever branch you're working on. I'll get around to merging thing soon.

**Comment by ysoh286** [comment]
@tmelliott  This might take a while to get to since exam season's lurking round the corner :frowning:. Will get back to you in two weeks time? I had thoughts about turning it into an HTMLwidget package, but that means another package to maintain....

**Comment by ysoh286** [comment]
@tmelliott  Managed to squeeze in some time! I've written this for now - but just checking if that's what is needed for Shiny? 

```
 # these three lines are in the exportHTML() function
 url <- file.path(getwd(), file)
  class(url) <- "inzHTML"
return(invisible(url))

#defining 'print' function:

print <- function(url, ...) UseMethod("print", url)
  
print.inzHTML <- function(url, viewer = getOption("viewer", utils::browseURL)) {
  
  if (!is.null(viewer)) 
    viewer(url)
  
  invisible(url)
}
  ```
... so when I print `fp`, it opens up in a browser, but if I do `print(fp,  viewer = NULL)`,  the URL's a character string that's invisible.`as.character(fp)` returns the file path for the URL.

**Comment by tmelliott** [comment]
That looks good. Hopefully @wilsonhsw can make that work.

**Comment by tmelliott** [comment]
I've had to stop this returning anything - it doesn't make sense for a `print` statement to "return" something. Instead, if you need the URL just use `as.character(fp)`.
