### ISSUE TITLE
URL path construction

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#31]
In `exportHTML()`, when `file` is an __absolute path__ (e.g., `/home/user/Documents/file.html`), the URL returned by the function is invalid: `/tmp/gibberish//home/user/Documents/file.html`.

__Reason__: `file.path(getwd(), file)` just pastes them together with OS specific separator.

__Quick fix__: I've replaced this with `normalizePath(file)` for now, which will return `file` if it's an absolute path, otherwise it will paste `getwd()` in front of the path. _HOWEVER_, it requires that the file already exists.
```{r}
## Where am I?
getwd()
[1] "/tmp/dir"

## What exists?
list.files()
[1] "myfile.html"

## Get the absolute path for file in working directory
normalizePath("myfile.html")
[1] "/tmp/dir/myfile.html"

## What exists in my Documents folder?
list.files("/home/user/Documents")
[1] "anotherfile.html"

## Normalizing an absolute path does nothing
normalizePath("/home/user/Documents/anotherfile.html")
[1] "/home/user/Documents/anotherfile.html"

## But if the file doesn't exist, I can't normalize it
normalizePath("anotherfile.html")
[1] "anotherfile.html"
Warning message:
In normalizePath("anotherfile.html") :
  path[1]="anotherfile.html": No such file or directory
```

This may or may not be a permanent solution, so when you get a chance play around and make sure the behaviour is still as you expect.

**Comment by ysoh286** [comment]
TODO: test if we can write all the files out in the correct file instead of sticking everything inline on a single HTML page.
