### ISSUE TITLE
Interactive Plot? Helper function

### ISSUE THREAD

**Issue by tmelliott** [iNZightVIT/iNZightPlots#53]
Some little function that runs the necessary "can this plot be interacted with?" logics and returns `TRUE` or `FALSE`. Something like ... 
```r
p <- iNZightPlot(x)
can.interact(p)
# [1] TRUE

p <- iNZightPlot(x, g1 = fct)
can.interact(p)
# [2] FALSE
```

**Comment by tmelliott** [comment]
@ysoh286 if you have time and this is trivial could you try get this going? Use-case is so the quick interact button on the plot toolbar is only shown when the plot can be interacted with.

**Comment by ysoh286** [comment]
@tmelliott  On it! Do you need it for the new iNZightMaps module as well, or only for plots plotted with iNZightPlots?

**Comment by tmelliott** [comment]
@ysoh286 Anything that's interactive - so any maps that work also. Basically anything passed in (even if it's not an iNZightPlot) should return FALSE (or TRUE if it is interactable).

Thanks!

**Comment by ysoh286** [comment]
@tmelliott  Ok. Do I still push to interact branch, or use hotfix branches and abandon interact?

**Comment by tmelliott** [comment]
Just use a feature branch (e.g., feature/interaction-helper). Hotfix = oh sh*t these needs to be fixed ASAP

**Comment by tmelliott** [comment]
@ysoh286 feature branches from dev (only hotfix should branch off master).
